Assassin set and Mana Pearl item db and function
themanaworld/tmwa-server-data pull request #580
Opened 2021-04-11 15:54 UTC by HoraK-FDF

- tweaked assassins set and added assassin mask, assassin ring, assassin amulet and the mana-pearl
- changed price of enchanters to be like other trinklets
- aligned trinklets db file

2021-04-13 13:05 UTC, pazkero commented on world/map/db/item_db_head.txt
> +5267,   AssassinMask,                   5,      30000,      3000,       10,         0,      16,     0,      -5,     0,      2,      256,        0,      0,      0,      {},
16 DEF is too much for the mask.
0 DEF and 16 EVD is better.

2021-04-13 13:10 UTC, pazkero commented on world/map/db/item_db_trinket.txt
> +5270,   ManaPearl,                      5,      0,          0,          0,          0,      0,      0,      11,     0,      2,      16,         0,      0,      0,      {},
111 MP is a lot; That's over half of what I currently have.

2021-04-13 13:11 UTC, pazkero commented on world/map/npc/items/manapearl_item.txt
> +    if (getgmlevel() >= 60)
Better use `if (debug)` then, or remove, but it is weird to allow GMs to equip the ring and get -7 agi.

Looks a lot like copy-paste

2021-04-13 13:14 UTC, pazkero requested changes
Please fix those and decide for style (HP or EVD, but NOT defense)

2021-04-13 20:56 UTC, HoraK-FDF commented on world/map/db/item_db_trinket.txt
> +5270,   ManaPearl,                      5,      0,          0,          0,          0,      0,      0,      11,     0,      2,      16,         0,      0,      0,      {},
55 MP now

2021-04-13 21:02 UTC, HoraK-FDF commented on world/map/db/item_db_head.txt
> +5267,   AssassinMask,                   5,      30000,      3000,       10,         0,      16,     0,      -5,     0,      2,      256,        0,      0,      0,      {},
reduced def to 6 (somehow I could not bear the thought of a 0 def item) and as you said 1 def = 7 hp i turned the remaining 10 def into 70 hp. i hope that's works for you.

2021-04-14 02:30 UTC, pazkero approved these changes
OK

2021-04-14 02:31 UTC, merged