brawling item check for focused brawling skill
themanaworld/tmwa-server-data pull request #584
Opened 2021-05-01 03:10 UTC by HoraK-FDF

On normal dex ranges assassin set with speed skill does more dps than brawling skill only on high dex brawling skill gets stronger again (62 dex). That will cause that many simply use speed skill with the set instead of brawling skill.

here some values with conc/iron pots:
str:99 agi:137=99+38 vit:86 int:1 dex:31=30+1 luk:75
brawling skill: 2586 dps
speed skill: 2760 dps
str:99 agi:137=99+38 vit:86 int:1 dex:100=99+1 luk:75
brawling skill: 3216 dps
speed skill: 2900 dps

2021-06-09 23:40 UTC, HoraK-FDF commented
with set bonus for 5 items of 15 str (3 for each) i reach:
str:99 agi:137=99+38 vit:86 int:1 dex:31=30+1 luk:75
brawling skill: 2907 dps
str:99 agi:137=99+38 vit:86 int:1 dex:100=99+1 luk:75
brawling skill: 3590 dps

with set bonus for 5 items of 10 str (2 for each) i reach:
str:99 agi:137=99+38 vit:86 int:1 dex:31=30+1 luk:75
brawling skill: 2736 dps
str:99 agi:137=99+38 vit:86 int:1 dex:100=99+1 luk:75
brawling skill: 3385 dps

2021-06-10 07:22 UTC, HoraK-FDF commented
with set bonus for 5 items of 10 str (2 for each) and 5 dex (1 for each) i reach:
str:99 agi:137=99+38 vit:86 int:1 dex:31=30+6 luk:75
brawling skill: 2780 dps
str:99 agi:137=99+38 vit:86 int:1 dex:100=99+6 luk:75
brawling skill: 3448 dps

2021-06-11 03:34 UTC, pazkero commented on world/map/npc/items/brawling_item.txt
> +    if (@skilllist_id[0] == SKILL_BRAWLING)
PS. Do not presume player has only Brawling focused.

Even TMWA allows you to focus all six skills at once, it just was kept disabled by staff because focus skills balance is terribly bad (and Fate's notes about when it was supposed to unlock the second level of focus skill.)

2021-07-28 00:15 UTC, pazkero requested changes

2021-07-28 00:15 UTC, pazkero commented on world/map/npc/items/brawling_item.txt
> +        bonus bCritical, 1;
It doesn't make much sense for a brawler to bypass defenses, to be honest...

2021-07-28 00:15 UTC, pazkero commented on world/map/npc/items/brawling_item.txt
> +        bonus bDex, 1;
Wouldn't bHit be better?

2021-07-28 00:15 UTC, pazkero commented on world/map/npc/items/brawling_item.txt
>      message strcharinfo(0), "This item's curse does not allow it to be used with weapons equipped.";
Off-topic:

1. This no longer makes sense and these items aren't Iilia-exclusive anymore.
2. You know the rules, MR in both Evolved and TMWA.

2021-12-03 23:17 UTC, merged